### ISSUE TITLE
no mathexercise.cls?

### ISSUE THREAD

**Issue by doublemoon-bird** [SwitWu/ODE-DingTongren-Solutions#1]

**Comment by doublemoon-bird** [comment]
> ![mathexercise](https://private-user-images.githubusercontent.com/174120239/373994347-71da8c1b-2984-450f-8252-cf9c9df6e87e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjQ4NTcsIm5iZiI6MTcyODI2NDU1NywicGF0aCI6Ii8xNzQxMjAyMzkvMzczOTk0MzQ3LTcxZGE4YzFiLTI5ODQtNDUwZi04MjUyLWNmOWM5ZGY2ZTg3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwMTI5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTJkNzZkOTFlYjBiMmE2NzY0NTAzZDllYzA5ZDYzMjgxZDE0NDc5YzQ4NDJkZjExNWI1YjMxOWQ3YzBhZWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O9OApConZQvToO_oMERTQ46lgQ3FUiRt_n3muBRDpls) I can't find mathexercise.cls in your repository.

**Comment by SwitWu** [comment]
PDF 里说明了
